### ISSUE TITLE
Design the logo for BizSync

### ISSUE THREAD

**Issue by Akki019** [upes-open/OSoC-24-BizSync#1]

**Comment by ParthDhavan04** [comment]
Kindly assign this to me.

**Comment by Akki019** [comment]
@ParthDhavan04 you can work on it

**Comment by cxde-Sujal** [comment]
Kindly assign it to me @Akki019

**Comment by shradiphylleia** [comment]
pls assign -looking at this mockup.
![Biz-Sync](https://github.com/upes-open/OSoC-24-BizSync/assets/118170804/ccf62e3c-7626-4079-a533-a2fe35c1ce8f)

**Comment by Akki019** [comment]
@shradiphylleia It looks good. Upload it in bizsync-application => public => Logo and put up a PR. You can also try some different color than black but overall it looks good

**Comment by Akki019** [comment]
@cxde-Sujal We have selected the design. You can go for other issues
