### ISSUE TITLE
Create an auth microservice

### ISSUE THREAD

**Issue by Akki019** [upes-open/OSoC-24-BizSync#10]
Develop auth microservice which can handle signup signin and authenticate user using express and mongoose.

**Comment by rampantvoid** [comment]
can you assign this to me

**Comment by Akki019** [comment]
@rampantvoid You can begin with the issue

**Comment by sakshammaggu** [comment]
@Akki019 hi i want to work on this issue

**Comment by shradiphylleia** [comment]
can you assign this to me.will be using jwt and bcrypt. cookie-parser for session cookies. Please let me know where to find the userModel and its specifications.

**Comment by Akki019** [comment]
@sakshammaggu You can work on it. In OPEN discord server, go to take-your-project channel and in topmost message react to first reaction. It will open workspace for bizsync

**Comment by Akki019** [comment]
@shradiphylleia You can work on it. For signup use Organisation name, email, password and for login email and password

**Comment by sakshammaggu** [comment]
@Akki019 i'm still not able to see the workspace section. and should I also use Jwt and bcryptJS for authenticating?
