### ISSUE TITLE
Dashboard UI Mockup

### ISSUE THREAD

**Issue by Akki019** [upes-open/OSoC-24-BizSync#12]
Description:
Create a mockup for the main dashboard UI. The design should include sections for the sidebar and main content. It should be visually appealing, user-friendly, and provide an overview of all key metrics.

Requirements:

Add Button:
Positioned at the top of the dashboard.
Design a button that opens a popup form for adding new entities (bill, spending, sale, worker, etc.).

Receivables Section:
Design a pie chart for overdue and soon-to-be overdue receivables.
Include details in a list or table format.
Provide a link to a detailed view of all receivables.

Spends Section:
Design a pie chart for overdue and soon-to-be overdue spends.
Include details in a list or table format.
Provide a link to a detailed view of all spends.

Inventory Alerts Section:
Design a list for items with low quantities.
Include item name, current quantity, and reorder level.
Provide a link to a detailed view of inventory items.

Expenses Pie Chart:
Design a pie chart showing expenses for the current month categorized by type.

Spends vs. Earnings Chart:
Design a line or bar chart showing spends vs. earnings over the last few months.

Notifications Section:
Design a section for displaying alerts for critical events (e.g., very low inventory, critical overdue payments).

**Comment by rampantvoid** [comment]
can you assign this issue to me

**Comment by Akki019** [comment]
@rampantvoid You can begin with it 
https://www.zoho.com/in/books/accounting-software-demo/#/home/dashboard
Take this for reference and also implement sidebar

**Comment by Akki019** [comment]
Completed in #44
