### ISSUE TITLE
Implement Dashboard UI

### ISSUE THREAD

**Issue by Akki019** [upes-open/OSoC-24-BizSync#13]
Description:
Implement the dashboard UI. The implementation should ensure a responsive, user-friendly interface.

Requirements:

Add Button:
Implement a button at the top of the dashboard.
Create a popup form for adding new entities (bill, spending, sale, worker, etc.).

Receivables Section:
Implement a pie chart for overdue and soon-to-be overdue receivables using Chart.js.
Include a table or list format for details.
Add a link to a detailed view of all receivables.

Spends Section:
Implement a pie chart for overdue and soon-to-be overdue spends using Chart.js.
Include a table or list format for details.
Add a link to a detailed view of all spends.

Inventory Alerts Section:
Implement a list for items with low quantities.
Include item name, current quantity, and reorder level.
Add a link to a detailed view of inventory items.

Expenses Pie Chart:
Implement a pie chart showing expenses for the current month categorized by type using Chart.js.

Spends vs. Earnings Chart:
Implement a line or bar chart showing spends vs. earnings over the last few months using Chart.js.

Notifications Section:
Implement a section for displaying alerts for critical events.

Libraries:

React, Redux, Chart.js, React-Chartjs-2, Material-UI, React-Modal

**Comment by Akki019** [comment]
@rampantvoid you can begin with it

**Comment by Akki019** [comment]
@rampantvoid Are you working on it?

**Comment by rampantvoid** [comment]
yes
