### ISSUE TITLE
Design Inventory Management Page UI

### ISSUE THREAD

**Issue by Akki019** [upes-open/OSoC-24-BizSync#14]
Create a mockup for the Inventory Management page. The design should include sections for viewing inventory items, adding new items, editing existing items, and low inventory alerts. Make it responsive

Requirements:

Inventory List Section:
Table displaying item name, current quantity, reorder level, and status (e.g., low, adequate). Items marked as low in inventory should be highlighted in red.

Add Item Button:
Button to open a form for adding new inventory items.

Edit Item Option:
Option to edit existing inventory items.

**Comment by ParthDhavan04** [comment]
i would like to work on this.

**Comment by tusharsaini590** [comment]
i would like to contribute on this

**Comment by shradiphylleia** [comment]
if the ui is still required pls assign.

**Comment by rampantvoid** [comment]
@Akki019 can you assign this issue to me i've made the ui
