### ISSUE TITLE
Implement Inventory Management Page UI

### ISSUE THREAD

**Issue by Akki019** [upes-open/OSoC-24-BizSync#15]
Implement the Inventory Management page based on the approved mockup. Ensure it is responsive and user-friendly.

Requirements:

Inventory List Section:
Implement a table to display inventory items with columns for item name, current quantity, reorder level, and status. Items marked as low in inventory should be styled with a red background or another visually distinct indicator.

Add Item Button:
Implement a button that opens a modal form for adding new inventory items. 

Edit Item Option:
Implement functionality to edit existing inventory items.

Low Inventory Alerts Section:
Implement a section to display items that are low in stock, with appropriate styling for low inventory items.

**Comment by cxde-Sujal** [comment]
Can you asign it to me ? Can i get a reference too

**Comment by iDream2** [comment]
Hey .... Can I be assigned this issue, as well ? I've finished one task till now, and would like to finish one more issue today . Thank You.

**Comment by Akki019** [comment]
@iDream2 You can work on this. Also your last PR could not be merged as someone else submitted it first. Also attach ss of mobile and desktop view in PR you raise

**Comment by ParthDhavan04** [comment]
can i work on this too?

**Comment by rampantvoid** [comment]
@Akki019 can you assign this to me

**Comment by rampantvoid** [comment]
@Akki019 i have the implementation ready, if you could assign me i'll raise a pr
