### ISSUE TITLE
Inventory Management API

### ISSUE THREAD

**Issue by Akki019** [upes-open/OSoC-24-BizSync#16]
Develop the backend API for Inventory Management, including endpoints for retrieving, adding, and updating inventory items.

Requirements:

GET /api/inventory: Retrieve a list of all inventory items.
POST /api/inventory: Add a new inventory item.
PUT /api/inventory/:id: Update an existing inventory item.
GET /api/inventory/low: Retrieve inventory items that are low in stock (for dashboard).

Database Schema:

Inventory Item:
name (String)
quantity (Number)
reorderLevel (Number)
status (String)

Perform unit testing using Postman.

**Comment by Akki019** [comment]
@shradiphylleia You can work on it. For now use mongodb local server. I'll provide atlas one soon

**Comment by rampantvoid** [comment]
@Akki019 can you assign this to me

**Comment by rampantvoid** [comment]
@Akki019 i have completed this i can raise a pr

**Comment by rampantvoid** [comment]
@Akki019 have raise pr, also accounted for the inventory being unique to each user, modiefied the existing schema by adding
user: {
     type:Schemas.Types.ObjectId,
     ref:"User"
}
