### ISSUE TITLE
Design Supplier Management Page UI

### ISSUE THREAD

**Issue by Akki019** [upes-open/OSoC-24-BizSync#17]
Create a mockup for the Supplier Management page. The design should include sections for viewing suppliers, adding new suppliers, and editing supplier details.

Requirements:

Supplier List Section:
Table displaying supplier name, contact information, and status.

Add Supplier Button:
Button to open a form for adding new suppliers.

Edit Supplier Option:
Option to edit existing supplier details.

**Comment by ParthDhavan04** [comment]
i would like to work on this.

**Comment by shradiphylleia** [comment]
if the ui is still required pls assign

**Comment by rampantvoid** [comment]
hi can you assign this to me

**Comment by rampantvoid** [comment]
@Akki019 have this ready, if you could assign me this i'll raise a pr
