### ISSUE TITLE
Implement Supplier Management Page UI

### ISSUE THREAD

**Issue by Akki019** [upes-open/OSoC-24-BizSync#18]
Implement the Supplier Management page based on the approved mockup. Ensure it is responsive and user-friendly.

Requirements:

Supplier List Section:
Implement a table to display suppliers with columns for name, contact information, and status.

Add Supplier Button:
Implement a button that opens a modal form for adding new suppliers.

Edit Supplier Option:
Implement functionality to edit existing supplier details.

**Comment by AbhishekJ24** [comment]
I want to work on this issue, is there any UI or figma files which we have to refer for the same

**Comment by Akki019** [comment]
> I want to work on this issue, is there any UI or figma files which we have to refer for the same

@AbhishekJ24 You can start with the issue. Connect on discord workspace I'll share you the reference

**Comment by AbhishekJ24** [comment]
okay, please let me know your discord handle/id

**Comment by Akki019** [comment]
> okay, please let me know your discord handle/id

In OPEN Discord channel, go to take-your-project and select finalproject02. It will open workspace of BizSync

**Comment by AbhishekJ24** [comment]
okay

**Comment by Akki019** [comment]
@AbhishekJ24 Are you working on it?

**Comment by ParthDhavan04** [comment]
can i work on this?

**Comment by rampantvoid** [comment]
@Akki019 hi can you assign this to me
