### ISSUE TITLE
Supplier Management API

### ISSUE THREAD

**Issue by Akki019** [upes-open/OSoC-24-BizSync#19]
Develop the backend API for Supplier Management, including endpoints for retrieving, adding, and updating supplier details.

Requirements:

GET /api/suppliers: Retrieve a list of all suppliers.
POST /api/suppliers: Add a new supplier.
PUT /api/suppliers/:id: Update an existing supplier.

Database Schema:

Supplier:
name (String)
contactInfo (Object)
email (String)
phone (String)
status (String)

Perform unit testing using Postman

**Comment by Saga690** [comment]
Can I work on this?

**Comment by Akki019** [comment]
@Saga690 You can work on this

**Comment by rampantvoid** [comment]
@Akki019 can you assign this to me

**Comment by shradiphylleia** [comment]
if available pls assign

**Comment by rampantvoid** [comment]
@Akki019 have made the apis, i can raise a pr asap, if you assign me

**Comment by rampantvoid** [comment]
@Akki019  have raise pr, also accounted for the supplier being unique to each user, modiefied the existing schema by adding
user: {
type:Schemas.Types.ObjectId,
ref:"User"
}
