### ISSUE TITLE
Create UI for homepage

### ISSUE THREAD

**Issue by Akki019** [upes-open/OSoC-24-BizSync#2]
Create a visually appealing and user-friendly mockup for the home page UI of our ERP system, including sections for the navbar, main content, and footer. Make it for desktop and mobile versions.

Sections to Include:

Navbar:
Logo, Navigation Links (Home, Features, Pricing, About Us, Contact Us, Login, Signup)

Main Content:
Hero Section: Headline, Subheadline, Call-to-Action Buttons
Features Section: List of Key Features with Icons/Illustrations
Testimonials Section: User Testimonials
Signup Call-to-Action: Headline, Signup Button
Additional Info Section: Benefits of the ERP System

Footer: 
Contact Information, Social Media Links

**Comment by rampantvoid** [comment]
Hi, can you assign this issue to me

**Comment by Akki019** [comment]
> Hi, can you assign this issue to me

@rampantvoid You can start working on this. Also drop a message on BizSync workspace and fork repo

**Comment by rampantvoid** [comment]
@Akki019 can you please check the pull request
