### ISSUE TITLE
Design Staff Management Page UI

### ISSUE THREAD

**Issue by Akki019** [upes-open/OSoC-24-BizSync#20]
Create a mockup for the Staff Management page. The design should include sections for viewing staff members, adding new staff members, editing staff details, and managing roles.

Requirements:

Staff List Section:
Table displaying staff name, position, contact information, and status.

Add Staff Button:
Button to open a form for adding new staff members.

Edit Staff Option:
Option to edit existing staff details.

Manage Roles Section:
Interface to assign or update roles for staff members.

**Comment by ParthDhavan04** [comment]
i would like to work on this.

**Comment by shradiphylleia** [comment]
if the ui is still required pls assign

**Comment by rampantvoid** [comment]
@Akki019 can you assign this to me

**Comment by rampantvoid** [comment]
@Akki019 have this ready, if you can assign me this i'll raise a pr
