### ISSUE TITLE
Implement Staff Management Page UI

### ISSUE THREAD

**Issue by Akki019** [upes-open/OSoC-24-BizSync#21]
Implement the Staff Management page based on the approved mockup. Ensure it is responsive and user-friendly.

Requirements:

Staff List Section:
Implement a table to display staff members with columns for name, position, contact information, and status.

Add Staff Button:
Implement a button that opens a modal form for adding new staff members.

Edit Staff Option:
Implement functionality to edit existing staff details.

Manage Roles Section:
Implement an interface to assign or update roles for staff members.

**Comment by the25thjin** [comment]
assign this to me imma try to do it also give me the reference 
@Akki019

**Comment by Akki019** [comment]
@the25thjin You can work on it. Take reference from dashboard ui design on discord. If you have any other issue we can connect on discord

**Comment by rampantvoid** [comment]
@Akki019  have this ready, if you can assign me this i'll raise a pr
