### ISSUE TITLE
Staff Management API

### ISSUE THREAD

**Issue by Akki019** [upes-open/OSoC-24-BizSync#22]
Develop the backend API for Staff Management, including endpoints for retrieving, adding, and updating staff details.

Requirements:

GET /api/staff: Retrieve a list of all staff members.
POST /api/staff: Add a new staff member.
PUT /api/staff/:id: Update an existing staff member.

Database Schema:

Staff Member:
name (String)
position (String)
contactInfo (Object) : email (String) and phone (String)
status (String)
roles (Array of Strings)

Perform unit testing using Postman

**Comment by shradiphylleia** [comment]
pls assign

**Comment by rampantvoid** [comment]
@Akki019 can you assign me this

**Comment by rampantvoid** [comment]
@Akki019 have made the apis, if you can assign me, ill raise a pr asap

**Comment by rampantvoid** [comment]
@Akki019  have raise pr, also accounted for the staffs being unique to each user, modiefied the existing schema by adding
user: {
type:Schemas.Types.ObjectId,
ref:"User"
}
