### ISSUE TITLE
Design Financial Management Page UI

### ISSUE THREAD

**Issue by Akki019** [upes-open/OSoC-24-BizSync#23]
Create a mockup for the Financial Management page. The design should include sections for viewing financial records, adding new records, editing existing records, and generating reports.

Requirements:

Financial Records Section:
Table displaying financial record type, amount, date, category, and status.

Add Record Button:
Button to open a form for adding new financial records.

Edit Record Option:
Option to edit existing financial records.

Generate Reports Section:
Interface to select report criteria and generate reports.

**Comment by ParthDhavan04** [comment]
can i work on this?

**Comment by shradiphylleia** [comment]
if the ui is still req. pls assign

**Comment by rampantvoid** [comment]
@Akki019 have this ready, if you can assign me i'll raise a pr
