### ISSUE TITLE
Implement Financial Management Page UI

### ISSUE THREAD

**Issue by Akki019** [upes-open/OSoC-24-BizSync#24]
Implement the Financial Management page based on the approved mockup. Ensure it is responsive and user-friendly.

Requirements:

Financial Records Section:
Implement a table to display financial records with columns for type, amount, date, category, and status.

Add Record Button:
Implement a button that opens a modal form for adding new financial records.

Edit Record Option:
Implement functionality to edit existing financial records.

Generate Reports Section:
Implement an interface to select report criteria and generate reports.

**Comment by rampantvoid** [comment]
@Akki019 can you assign this to me

**Comment by ParthDhavan04** [comment]
i would like to work on this

**Comment by rampantvoid** [comment]
@Akki019 have this ready, if you can assign me i'll raise a pr
