### ISSUE TITLE
Financial Management API

### ISSUE THREAD

**Issue by Akki019** [upes-open/OSoC-24-BizSync#25]
Develop the backend API for Financial Management, including endpoints for retrieving, adding, and updating financial records, as well as generating reports.

Requirements:

GET /api/financials: Retrieve a list of all financial records.
POST /api/financials: Add a new financial record.
PUT /api/financials/:id: Update an existing financial record.
GET /api/reports: Retrieve reports based on selected criteria.

Database Schema:

Financial Record:
type (String)
amount (Number)
date (Date)
category (String)
status (String)

Perform unit testing using Postman

**Comment by shradiphylleia** [comment]
pls assign

**Comment by rampantvoid** [comment]
@Akki019 can you assign me this
