### ISSUE TITLE
Design Reports Page UI

### ISSUE THREAD

**Issue by Akki019** [upes-open/OSoC-24-BizSync#26]
Create a mockup for the Reporting page. The design should include sections for generating various types of reports based on financial data, staff performance, inventory status, and sales analytics.

Requirements:

Financial Reports Section:
Interface to select financial report criteria (e.g., date range, category) and generate reports.
Staff Performance Reports Section:
Interface to generate reports on staff performance metrics (e.g., sales performance, attendance).
Inventory Reports Section:
Interface to generate reports on inventory status (e.g., low inventory items, stock levels).
Sales Analytics Section:
Charts and graphs to visualize sales data over time, by product category, etc.

**Comment by ParthDhavan04** [comment]
i would like to work on this.

**Comment by Akki019** [comment]
@ParthDhavan04 You can work on this

**Comment by ParthDhavan04** [comment]
Hi. Can you pls connect on Discord. I have some questions .

**Comment by rampantvoid** [comment]
@Akki019 have this ready, if you can assign me i'll raise a pr
