### ISSUE TITLE
Implement Reporting Page UI

### ISSUE THREAD

**Issue by Akki019** [upes-open/OSoC-24-BizSync#27]
Implement the Reporting page based on the approved mockup. Ensure it includes sections for generating various types of reports based on financial data, staff performance, inventory status, and sales analytics. Use Redux and chart.js

Requirements:

Financial Reports Section:
Implement an interface to select financial report criteria (e.g., date range, category) and generate reports.
Staff Performance Reports Section:
Implement functionality to generate reports on staff performance metrics (e.g., sales performance, attendance).
Inventory Reports Section:
Implement an interface to generate reports on inventory status (e.g., low inventory items, stock levels).
Sales Analytics Section:
Implement charts and graphs to visualize sales data over time, by product category, etc.

**Comment by ParthDhavan04** [comment]
i would like to work on this

**Comment by rampantvoid** [comment]
@Akki019 have this ready, if you can assign me i'll raise a pr
