### ISSUE TITLE
Reports API

### ISSUE THREAD

**Issue by Akki019** [upes-open/OSoC-24-BizSync#28]
Develop the backend APIs for generating reports based on financial data, staff performance metrics, inventory status, and sales analytics.

Requirements:

GET /api/reports/financial: Endpoint to generate financial reports based on selected criteria (e.g., date range, category).
GET /api/reports/staff: Endpoint to generate staff performance reports (e.g., sales performance, attendance).
GET /api/reports/inventory: Endpoint to generate inventory status reports (e.g., low inventory items, stock levels).
GET /api/reports/sales: Endpoint to retrieve sales analytics data (e.g., sales trends, product category sales).

Perform unit testing using Postman

**Comment by shradiphylleia** [comment]
pls assign

**Comment by rampantvoid** [comment]
hi can you assign this to me
