### ISSUE TITLE
Design Sales Management Page UI

### ISSUE THREAD

**Issue by Akki019** [upes-open/OSoC-24-BizSync#29]
Create a mockup for the Sales Management page. The design should include sections for managing sales orders, viewing customer details, handling returns, and generating sales reports.

Requirements:

Sales Orders Section:
Table displaying sales order details such as order number, date, customer name, total amount, and status.
Customer Details Section:
Interface to view and manage customer details linked to sales orders.
Returns Section:
Interface to process returns and manage return transactions.
Sales Reports Section:
Interface to generate reports on sales performance, trends, and customer analytics.

**Comment by ParthDhavan04** [comment]
can i work on this

**Comment by rampantvoid** [comment]
@Akki019 have this ready, if you can assign this to me ill raise a pr
