### ISSUE TITLE
Implement Navbar Component

### ISSUE THREAD

**Issue by Akki019** [upes-open/OSoC-24-BizSync#3]
Develop a responsive navbar component

**Comment by rampantvoid** [comment]
Can you please assign this issue to me

**Comment by Saga690** [comment]
Would like to work on this

**Comment by ParthDhavan04** [comment]
I would like to work on this issue. Please provide the UI.

**Comment by Akki019** [comment]
@rampantvoid @Saga690 @ParthDhavan04 You all can work on it. Whoever submits PR with good commit first will be awarded points.
https://www.figma.com/design/Oh4WjqNQdapx4jM3N5mOyu/Untitled?t=F6mdqJse5nSvTlj7-1

**Comment by Saga690** [comment]
Raised a PR!
