### ISSUE TITLE
Implement Sales Management Page UI

### ISSUE THREAD

**Issue by Akki019** [upes-open/OSoC-24-BizSync#30]
Implement a responsive Sales Management page. Ensure it includes sections for managing sales orders, viewing customer details, handling returns.

Requirements:

Sales Orders Section:
Implement a table to display sales order details such as order number, date, customer name, total amount, and status.
Customer Details Section:
Implement functionality to view and manage customer details linked to sales orders.
Returns Section:
Implement interfaces and workflows to process returns and manage return transactions.

**Comment by ParthDhavan04** [comment]
can i work on this?

**Comment by rampantvoid** [comment]
@Akki019 have this ready, if you can assign this to me ill raise a pr
