### ISSUE TITLE
Sales Management API

### ISSUE THREAD

**Issue by Akki019** [upes-open/OSoC-24-BizSync#31]
Develop the backend APIs for managing sales orders, customer details, returns, and generating sales reports.

Requirements:

GET /api/sales/orders: Endpoint to retrieve a list of sales orders with details.
GET /api/customers/:id: Endpoint to retrieve customer details for a specific customer.
POST /api/returns: Endpoint to process returns and update corresponding sales order status.
GET /api/reports/sales: Endpoint to generate sales reports based on selected criteria (e.g., date range, product category).

Database Schema:

Sales Order:
orderNumber (String)
date (Date)
customer (Object: { name: String, email: String, phone: String })
items (Array of Objects: { productId: String, quantity: Number, unitPrice: Number })
totalAmount (Number)
status (String)

Perform unit testing using Postman

**Comment by Siddharthaaa21** [comment]
would like to work on it

**Comment by Akki019** [comment]
@Siddharthaaa21 You can work on it. If you want to discuss further we can connect on discord

**Comment by Siddharthaaa21** [comment]
alright

**Comment by shradiphylleia** [comment]
pls assign.

**Comment by Akki019** [comment]
@shradiphylleia You can begin with it

**Comment by rampantvoid** [comment]
hi can you assign this to me
