### ISSUE TITLE
Implement footer component

### ISSUE THREAD

**Issue by Akki019** [upes-open/OSoC-24-BizSync#5]
Develop footer component

**Comment by ParthDhavan04** [comment]
I would like to work on this issue. Please provide the UI.

**Comment by Akki019** [comment]
@ParthDhavan04 You can begin with this issue. 
https://www.figma.com/design/Oh4WjqNQdapx4jM3N5mOyu/Untitled?t=F6mdqJse5nSvTlj7-1

**Comment by ParthDhavan04** [comment]
I have generated the PR.Kindly check.

**Comment by rampantvoid** [comment]
can you also assign this to me already have working model

**Comment by Akki019** [comment]
@rampantvoid you can work on it
