### ISSUE TITLE
Design Signup and Sign in pages UI

### ISSUE THREAD

**Issue by Akki019** [upes-open/OSoC-24-BizSync#6]
Create a mockup for the signup and signin pages UI. The design should be user-friendly.

Signup : Include fields for  username, email, company name, password, and password confirmation.

Signin : Include fields for email and password, as well as a link to reset the password.

**Comment by Donniedarko45** [comment]
hey I am up for this can I use for that?

**Comment by Akki019** [comment]
> hey I am up for this can I use React for that?

This is for figma wireframe design. Issue #7 is for react code for the same. You can comment under that for react

**Comment by rampantvoid** [comment]
can you assign this to me

**Comment by Akki019** [comment]
@rampantvoid you can begin with this issue

**Comment by Akki019** [comment]
Signup and signin pages implemented with design
