### ISSUE TITLE
Implement Signup and Signin pages

### ISSUE THREAD

**Issue by Akki019** [upes-open/OSoC-24-BizSync#7]
Develop signup and signin pages with appropriate fields according to UI

**Comment by Donniedarko45** [comment]
hey I am up for that can I use react for that.

**Comment by the25thjin** [comment]
i would like  to work on this as well using react

**Comment by the25thjin** [comment]
willl you provide us a design first?

**Comment by Akki019** [comment]
> hey I am up for that can I use react for that.

@Donniedarko45 You can begin with this issue. Ping me on Discord workspace channel of BizSync. I'll send you reference for this

**Comment by Akki019** [comment]
> i would like to work on this as well using react

@the25thjin This issue has been assigned to someone else. I'll be assigning you the other issue you commented on

**Comment by Donniedarko45** [comment]
> BizSync.
hey can you give a invite link of channel

**Comment by Akki019** [comment]
> > BizSync.
> > hey can you give a invite link of channel

In OPEN Discord channel, go to take-your-project and select finalproject02. It will open workspace of BizSync

**Comment by iDream2** [comment]
Hey! Can I be assigned this issue as well ? I have had worked on React before would like to contribute to the issue

**Comment by Akki019** [comment]
@iDream2 You can also work on this issue. Whoever submits first good commit will be rewarded points. I have shared reference for it on OPEN Discord channel in BizSync workspace go through that

**Comment by rampantvoid** [comment]
can you assign me this

**Comment by Akki019** [comment]
@rampantvoid you can begin with this issue
