### ISSUE TITLE
Implement Contact us page

### ISSUE THREAD

**Issue by Akki019** [upes-open/OSoC-24-BizSync#9]
Develop contact us page according to UI

**Comment by the25thjin** [comment]
i would like to work on this as well

**Comment by Akki019** [comment]
> i would like to work on this as well

@the25thjin You can begin with this issue. Ping me on Discord BizSync workspace channel I'll send you reference for it

**Comment by iDream2** [comment]
Hey! a bit late...but I would like to be assigned this issue as well. I have had experience working with React and would like to work on this.

**Comment by Akki019** [comment]
@iDream2 You can also work on this issue. Whoever submits first good commit will be rewarded points. I have shared reference for it on OPEN Discord channel in BizSync workspace go through that

**Comment by iDream2** [comment]
Hey @Akki019 , I could only find the announcements page for BizSync. Where I can have a look at the mockup design ? Should I PM you ?

**Comment by Akki019** [comment]
done in pr #45
